### PR TITLE
Implement shouldUpdate to avoid unnecessary component remounts

### PR DESCRIPTION
**Pull request by abdyer**
I based this on the implementation for [ImageSpec](https://github.com/facebook/litho/blob/c22fb44f31ece657f693fa9c4bed59cef2e176e6/litho-widget/src/main/java/com/facebook/litho/widget/ImageSpec.java) in the Litho repo. It's debatable which props should be included in the check, but hopefully this helps others avoid the image flicker I issue I ran into.

### CODE REVIEW

**Comment by pavlospt** [comment]
@abdyer The conversation on this issue with Andy Street involved the `isPureRender=true`  as well. Isn't that needed anymore?

**Comment by abdyer** [comment]
@pavlospt Thanks for the reminder. I had it in my working code, but we're not using this library directly so I forgot to include it here. Added.

**Comment by pavlospt** [comment]
@abdyer Great!

**Comment by charbgr** [comment]
Thanks @abdyer ! Looks good to me! I will merge it but I will not upload an artifact due to some bintray issues I face. I will try to solve them on the weekend! Maybe it will require to change the package name to solve the issue(maybe: com.github.charbgr:litho-picasso2:1.0)

I am also thinking of bumping the litho version and upload then the artifact. 
What do you think @pavlospt @abdyer?

**Review by charbgr — APPROVED** [review]

**Comment by pavlospt** [comment]
@charbgr yeap bumping the version as well would be nice!

**Comment by charbgr** [comment]
Friendly ping.. It is up under `com.github.charbgr:litho-picassox:1.0` and with AndroidX support! :) @pavlospt @abdyer 

Thanks @abdyer for the contribution!

**Pull request merged**
